import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
import { pathToFileURL } from 'node:url';
const { PGlite } = await import(pathToFileURL(process.argv[2]).href);
const db = new PGlite();
const c='10000000-0000-0000-0000-000000000001',t='10000000-0000-0000-0000-000000000002',u='10000000-0000-0000-0000-000000000003',w='10000000-0000-0000-0000-000000000004',q='10000000-0000-0000-0000-000000000005',m='10000000-0000-0000-0000-000000000006',d='10000000-0000-0000-0000-000000000007',s='10000000-0000-0000-0000-000000000008',req='10000000-0000-0000-0000-000000000009';
await db.exec(`create schema private;create schema auth;create schema storage;
create function auth.uid() returns uuid language sql as $$select '${u}'::uuid$$;
create table companies(id uuid,name text);
create table company_members(company_id uuid,user_id uuid,role text);
create table workers(id uuid,company_id uuid,name text,status text,kana text,phone text,email text,affiliation text,role text,experience_years numeric);
create table qualification_master(id uuid,company_id uuid,name text,issuer text);
create table worker_qualifications(id uuid,company_id uuid,worker_id uuid,qualification_master_id uuid,certificate_number text,issuer text,issued_at date,expires_at date,notes text,attachment_path text,attachment_back_path text,attachment_extra_paths text[] not null default '{}');
create table company_required_documents(id uuid,company_id uuid,name text,attachment_path text,attachment_paths text[],expires_at date,is_active boolean,scope text);
create table document_requirements(id uuid,company_id uuid,name text,scope text,is_active boolean);
create table worker_document_statuses(id uuid,company_id uuid,worker_id uuid,requirement_id uuid,attachment_path text,attachment_paths text[],expires_at date,status text);
create table partner_archive_folders(id uuid,company_id uuid,name text,parent_id uuid);
create table partner_archive_documents(id uuid,company_id uuid,name text,attachment_path text,expires_at date,is_active boolean,folder_id uuid);
create table storage.objects(bucket_id text,name text);
create table private.document_receive_codes(code uuid primary key,company_id uuid,expires_at timestamptz,used_at timestamptz,created_by uuid);
create table private.document_deliveries(id uuid primary key,sender_company_id uuid,recipient_company_id uuid,sender_name text,recipient_name text,sent_by uuid,note text,created_at timestamptz default now());
create table private.document_delivery_items(id uuid default gen_random_uuid(),delivery_id uuid,name text,bucket text,path text,company_path jsonb,source_item_id uuid,expires_at date);
create table private.company_data_delivery_items(id uuid default gen_random_uuid(),delivery_id uuid,payload_kind text,payload jsonb,company_path jsonb,source_item_id uuid,created_at timestamptz default now());
create table app_notifications(company_id uuid,recipient_user_id uuid,kind text,title text,body text,action_key text,action_id uuid);
insert into companies values('${c}','sender'),('${t}','receiver');
insert into company_members values('${c}','${u}','owner');
insert into workers(id,company_id,name,status) values('${w}','${c}','worker','active');
insert into qualification_master values('${m}','${c}','qualification','issuer');
insert into worker_qualifications(id,company_id,worker_id,qualification_master_id,attachment_path,attachment_back_path,attachment_extra_paths) values('${q}','${c}','${w}','${m}','front.jpg','back.jpg',array['extra1.jpg','extra2.jpg']);
insert into company_required_documents values('${d}','${c}','company-document','company1.jpg',array['company1.jpg','company2.jpg'],null,true,'upstream');
insert into document_requirements values('${req}','${c}','required-document','upstream',true);
insert into worker_document_statuses values('${s}','${c}','${w}','${req}','worker1.jpg',array['worker1.jpg','worker2.jpg','worker3.jpg'],null,'submitted');
insert into storage.objects values('qualification-certificates','front.jpg'),('qualification-certificates','back.jpg'),('qualification-certificates','extra1.jpg'),('qualification-certificates','extra2.jpg'),('company-required-documents','company1.jpg'),('company-required-documents','company2.jpg'),('worker-documents','worker1.jpg'),('worker-documents','worker2.jpg'),('worker-documents','worker3.jpg');`);
await db.exec(readFileSync('supabase/migrations/20261010222901_send_qualification_extra_photo_snapshots.sql','utf8'));
async function send(kind,id) {
 const code=(await db.query('select gen_random_uuid() id')).rows[0].id;
 const delivery=(await db.query('select gen_random_uuid() id')).rows[0].id;
 await db.query("insert into private.document_receive_codes(code,company_id,expires_at) values($1,$2,now()+interval '1 day')",[code,t]);
 const data={request_id:delivery,code,items:[{kind,id}]};
 await db.query("select private.company_document_exchange('send',$1::jsonb)",[JSON.stringify(data)]);
 return {delivery,code,data};
}
const qual=await send('worker_qualification',q);
assert.deepEqual((await db.query('select path from private.document_delivery_items where delivery_id=$1 order by path',[qual.delivery])).rows.map(r=>r.path),['back.jpg','extra1.jpg','extra2.jpg','front.jpg']);
assert.deepEqual((await db.query('select payload from private.company_data_delivery_items where delivery_id=$1',[qual.delivery])).rows[0].payload.attachment_paths,['front.jpg','back.jpg','extra1.jpg','extra2.jpg']);
await db.query("select private.company_document_exchange('send',$1::jsonb)",[JSON.stringify(qual.data)]);
assert.equal((await db.query('select count(*) n from private.document_delivery_items where delivery_id=$1',[qual.delivery])).rows[0].n,4);
const company=await send('company',d);
assert.equal((await db.query('select count(*) n from private.document_delivery_items where delivery_id=$1',[company.delivery])).rows[0].n,2);
const worker=await send('worker_document',s);
assert.equal((await db.query('select count(*) n from private.document_delivery_items where delivery_id=$1',[worker.delivery])).rows[0].n,3);
const bundle=await send('worker_personnel',w);
assert.equal((await db.query('select count(*) n from private.document_delivery_items where delivery_id=$1',[bundle.delivery])).rows[0].n,7);
await db.query('update worker_qualifications set attachment_extra_paths=$1 where id=$2',[['missing.jpg'],q]);
await assert.rejects(send('worker_qualification',q),/資格証追加写真ファイルが見つかりません/);
assert.deepEqual((await db.query('select payload from private.company_data_delivery_items where delivery_id=$1',[qual.delivery])).rows[0].payload.attachment_paths,['front.jpg','back.jpg','extra1.jpg','extra2.jpg']);
assert.equal((await db.query('select count(*) n from private.document_deliveries')).rows[0].n,4);
await db.query('update company_required_documents set attachment_paths=$1 where id=$2',[[],d]);
const legacy=await send('company',d);
assert.equal((await db.query('select count(*) n from private.document_delivery_items where delivery_id=$1',[legacy.delivery])).rows[0].n,1);
console.log('PASS exchange: qualification all-photo snapshot, company/worker all photos, personnel bundle, idempotent retry, missing-file transactional rollback, legacy fallback, prior snapshot immutable');
await db.close();
