import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
const {PGlite}=await import(pathToFileURL(process.argv[2]).href);
const text=async p=>fs.readFile(new URL('../'+p,import.meta.url),'utf8');
const workerMigration=process.argv[3] ? await fs.readFile(process.argv[3],'utf8') : null;
const migration=await text('supabase/migrations/20261011033318_qualification_prepared_photo_upload.sql');
for (const workerFirst of [true,false]) {
 const db=new PGlite();
 await db.exec(await text('tool/fixtures/qualification_photo_submission/schema.sql'));
 await db.exec(await text('tool/fixtures/qualification_photo_submission/live_functions.sql'));
 await db.exec(await text('supabase/migrations/20261010222157_add_qualification_certificate_extra_photos.sql'));
 await db.exec(await text('supabase/migrations/20261010222753_protect_qualification_photo_snapshots.sql'));
 await db.exec(await text('supabase/migrations/20261010233011_personal_qualification_photo_submission.sql'));
 await db.exec(`alter table workers add column status text default 'active';
 create function private.account_access_allowed() returns boolean language sql stable as $$select coalesce(current_setting('test.active',true),'true')='true'$$;
 create function private.license_document_upload_allowed(text) returns boolean language sql stable as $$select false$$;
 create function private.try_uuid(text) returns uuid language sql immutable as $$select case when $1 ~ '^[0-9a-f-]{36}$' then $1::uuid else null end$$;
 create function private.has_company_feature(uuid,text) returns boolean language sql stable as $$select false$$;
 create table document_requirements(id uuid,company_id uuid,is_active boolean);
 create table worker_document_statuses(id uuid,company_id uuid,worker_id uuid,requirement_id uuid,attachment_paths text[]);
 create table worker_document_status_history(attachment_paths text[]);
 grant select on document_requirements,worker_document_statuses,company_members to authenticated;
 create schema income_tax_private;
 create function income_tax_private.pdf_object_access(text) returns boolean language sql stable as $$select false$$;
 create function storage.allow_any_operation(text[]) returns boolean language sql stable as $$select false$$;
 create function private.company_content_review_enabled(uuid) returns boolean language sql stable as $$select true$$;
 create function private.content_file_unreferenced(text,text) returns boolean language sql stable as $$select false$$;
 create policy qualification_submission_upload on storage.objects for insert to authenticated with check(bucket_id='qualification-certificates' and private.qualification_submission_access(name,true));
 create policy worker_submission_upload on storage.objects for insert to authenticated with check(bucket_id='worker-documents');
 create policy account_deletion_access_guard on storage.objects as restrictive for all to authenticated using((select private.account_access_allowed())) with check((select private.account_access_allowed()));
 create policy income_tax_pdf_insert_guard on storage.objects as restrictive for insert to authenticated with check(bucket_id <> 'company-income-tax-tables' or (income_tax_private.pdf_object_access(name) and storage.allow_any_operation(array['object.upload'])));
 create policy \"review no media replacement insert\" on storage.objects as restrictive for insert to authenticated with check(not private.company_content_review_enabled(private.try_uuid(split_part(name,'/',1))) or bucket_id not in ('chat-attachments','communication-notes','communication-albums') or private.content_file_unreferenced(bucket_id,name));
 create policy income_tax_pdf_no_anon on storage.objects as restrictive for all to anon using(false) with check(false);
 create policy initial_beta_official_documents_insert_pause on storage.objects as restrictive for insert to public
 with check(bucket_id not in ('worker-documents','qualification-certificates','employee-onboarding-documents') or current_user='authenticated');
 create policy license_document_pilot_insert_scope on storage.objects as restrictive for insert to authenticated
 with check(bucket_id not in ('worker-documents','qualification-certificates','employee-onboarding-documents') or (bucket_id='worker-documents' and auth.uid() is not null and private.license_document_upload_allowed(name)));`);
 if(!workerMigration) await db.exec("create function private.worker_document_photo_upload_allowed(text) returns boolean language sql stable as $$select $1='worker-prepared'$$");
 const workerPatch=workerMigration ?? `do $$declare e text;begin select pg_get_expr(polwithcheck,polrelid) into e from pg_policy where polname='license_document_pilot_insert_scope';execute 'alter policy license_document_pilot_insert_scope on storage.objects with check (('||e||') or (bucket_id=''worker-documents'' and private.worker_document_photo_upload_allowed(name)))';end$$;`;
 if(workerFirst) await db.exec(workerPatch);
 await db.exec(migration);
 if(!workerFirst) await db.exec(workerPatch);
 const [company,user,other,worker,master,target,request]=Array.from({length:7},(_,i)=>`10000000-0000-0000-0000-${String(i+1).padStart(12,'0')}`);
 await db.exec(`insert into companies values('${company}');insert into company_members values('${company}','${user}','member'),('${company}','${other}','member');
 insert into workers(id,company_id,user_id) values('${worker}','${company}','${user}');insert into qualification_master values('${master}','${company}','qualification',false);
 insert into worker_qualifications(id,company_id,worker_id,qualification_master_id) values('${target}','${company}','${worker}','${master}');
 set test.uid='${user}';set role authenticated;`);
 const rpc=async(action,data={})=>(await db.query('select private.personal_qualification_submission($1,$2::jsonb) v',[action,JSON.stringify(data)])).rows[0].v;
 assert.equal((await rpc('photo_capability')).photo_upload_allowed,true);
 const prepared=await rpc('prepare_photos',{target_id:target,request_id:request,photo_slots:[{extension:'jpg'},{extension:'png'},{extension:'jpg'}]});
 for(const path of prepared.photo_paths) await db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['qualification-certificates',path]);
 await assert.rejects(db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['qualification-certificates',`${company}/${worker}/${target}/unprepared.jpg`]),e=>e.code==='42501');
 await db.exec(`set test.uid='${other}'`);
 assert.equal((await rpc('photo_capability')).photo_upload_allowed,false);
 await assert.rejects(db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['qualification-certificates',prepared.photo_paths[0]]),e=>e.code==='42501');
 await db.exec(`set test.uid='${user}';set test.active='false'`);
 assert.equal((await rpc('photo_capability')).photo_upload_allowed,false);
 assert.equal((await db.query('select private.qualification_photo_draft_upload_allowed($1) v',[prepared.photo_paths[0]])).rows[0].v,false);
 await db.exec(`set test.active='true'`);
 await rpc('submit',{id:request});
 assert.equal((await db.query('select private.qualification_photo_draft_upload_allowed($1) v',[prepared.photo_paths[0]])).rows[0].v,false);
 assert.equal((await db.query('delete from storage.objects where bucket_id=$1 returning id',['qualification-certificates'])).rows.length,0);
 if(workerMigration) {
  await db.exec('reset role');await db.exec(`insert into document_requirements values('${master}','${company}',true);set role authenticated;`);
  await db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['worker-documents',`${company}/${worker}/${master}/own-upload/photo.jpg`]);
 } else await db.query("insert into storage.objects(bucket_id,name) values('worker-documents','worker-prepared')");
 await assert.rejects(db.query("insert into storage.objects(bucket_id,name) values('employee-onboarding-documents','blocked')"),e=>e.code==='42501');
 await db.exec('reset role');
 await db.exec('alter policy income_tax_pdf_insert_guard on storage.objects with check(false)');
 await db.exec('set role authenticated');
 assert.equal((await rpc('photo_capability')).photo_upload_allowed,false);
 await db.exec('reset role');
 await db.exec("alter policy income_tax_pdf_insert_guard on storage.objects with check(bucket_id <> 'company-income-tax-tables' or (income_tax_private.pdf_object_access(name) and storage.allow_any_operation(array['object.upload'])))");
 await db.exec('set role authenticated');
 assert.equal((await rpc('photo_capability')).photo_upload_allowed,true);
 await db.exec('reset role');
 await db.exec("create policy unknown_pause on storage.objects as restrictive for insert to authenticated with check(false)");
 await db.exec(`set role authenticated`);
 assert.equal((await rpc('photo_capability')).photo_upload_allowed,false);
 await db.close();
}
console.log('Prepared qualification upload scope, account/actor/state rejection, retention and both policy composition orders: PASS');
