import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const {PGlite}=await import(process.argv[2]);
const db=new PGlite();
await db.exec(await fs.readFile(new URL('./fixtures/route_journey_capture/schema.sql',import.meta.url),'utf8'));
await db.exec(await fs.readFile(new URL('../supabase/migrations/20261008204012_route_journey_capture_staged.sql',import.meta.url),'utf8'));
const ids=Array.from({length:15},(_,i)=>`00000000-0000-0000-0000-${String(i+1).padStart(12,'0')}`);
const [company,user,other,worker,route,stop,source,report,capture,stop2,capture2,foreignCompany,foreignWorker,foreignSource,foreignStop]=ids;
await db.exec(`set test.uid='${user}'; insert into companies values('${company}'),('${foreignCompany}'); insert into company_members values('${company}','${user}','member'),('${company}','${other}','member'); insert into workers values('${worker}','${company}','${user}','本人','active'),('${foreignWorker}','${foreignCompany}','${other}','別会社','active'); insert into route_assignments values('${route}','${company}'); insert into route_stops values('${stop}','${route}',null,1,'計画住所','現場1'),('${stop2}','${route}',null,2,'計画住所2','現場2'),('${foreignStop}',gen_random_uuid(),null,1,'別のルート','別'); insert into attendance_verifications values('${source}','${company}','${worker}',null,'${route}','2026-09-30','clock_in',null,null,'location_photo',1),('${foreignSource}','${foreignCompany}','${foreignWorker}',null,'${route}','2026-09-30','clock_in',null,null,'location_photo',1); insert into daily_reports values('${report}','${company}',null,'${route}','2026-09-30','${user}','draft'); insert into daily_report_workers values('${report}','${worker}');`);
const json = value => `'${JSON.stringify(value).replaceAll("'","''")}'::jsonb`;
const failure={capture_contract_version:1,gps_capture_status:'failed',photo_capture_status:'failed',gps_captured_at:null,photo_captured_at:null,photo_observed_at:null,captured_address:null,latitude:null,longitude:null,accuracy_m:null,photo_storage_path:null,attempted_at:'2026-10-01T00:01:00Z'};
const save=(id,stopId=stop,payload=failure,origin='company',sourceId=source)=>db.query(`select public.save_route_journey_capture('${id}','${sourceId}','${stopId}','${origin}',${json(payload)}) v`);
await db.exec('set role authenticated');
assert.equal((await db.query(`select public.route_journey_workspace('${source}') v`)).rows[0].v.enabled,false);
await assert.rejects(save(capture),/disabled/);
await assert.rejects(db.exec(`insert into storage.objects(bucket_id,name) values('attendance-route-evidence','${company}/attendance/${route}/${worker}/${source}/off.jpg')`),/row-level security/);
await db.exec('reset role'); await db.exec(`insert into private.route_journey_rollouts values('${company}',true)`); await db.exec('set role authenticated');
const row=(await save(capture)).rows[0].v;
assert.equal(row.work_date,'2026-09-30');assert.equal(row.payload.captured_address,null);assert.equal(row.stop_label,'現場1');assert.equal(row.origin_kind,'company');
assert.equal((await save(capture)).rows[0].v.id,capture);
await assert.rejects(save(capture,stop,{...failure,captured_address:'invented'}),/mismatch/);
await assert.rejects(save(capture2,foreignStop),/actual route stop/);
await assert.rejects(save(capture2,stop2,failure,'direct'),/origin immutable/);
await assert.rejects(save(capture2,stop2,{...failure,captured_address:'計画住所'}),/cannot invent/);
await assert.rejects(save(capture2,stop2,{...failure,work_date:'2026-10-01'}),/payload/);
const path=`${company}/attendance/${route}/${worker}/${source}/capture.jpg`;
await db.exec(`insert into storage.objects(bucket_id,name) values('attendance-route-evidence','${path}')`);
const live={...failure,gps_capture_status:'acquired',photo_capture_status:'uploaded',gps_captured_at:'2026-10-01T00:02:00Z',photo_captured_at:null,photo_observed_at:'2026-10-01T00:02:00Z',captured_address:'実GPS取得住所',latitude:35.1,longitude:139.2,accuracy_m:5,photo_storage_path:path};
for (const [key,value] of [['accuracy_m',-1],['accuracy_m','NaN'],['gps_captured_at','infinity'],['photo_captured_at','-infinity'],['photo_observed_at','infinity'],['attempted_at','-infinity']]) {
 await assert.rejects(save(capture2,stop2,{...live,[key]:value}),/finite|types invalid/);
}
const second=(await save(capture2,stop2,live)).rows[0].v;assert.equal(second.payload.photo_captured_at,null);assert.equal(second.payload.captured_address,'実GPS取得住所');
await db.exec(`set test.uid='${other}'`);
assert.equal((await db.query(`select public.route_journey_capture_exact('${capture}') v`)).rows[0].v,null);
await assert.rejects(save(capture),/mismatch/);await assert.rejects(db.query(`select public.route_journey_workspace('${source}')`),/personal/);
assert.equal((await db.query(`select count(*)::int n from storage.objects where bucket_id='attendance-route-evidence'`)).rows[0].n,0);
await assert.rejects(db.exec(`insert into storage.objects(bucket_id,name) values('attendance-route-evidence','${path}.spoof')`),/row-level security/);
await db.exec(`set test.uid='${user}'; set test.allowed='false'`);await assert.rejects(db.query(`select public.route_journey_capture_exact('${capture}')`),/account/);await db.exec("set test.allowed='true'");
assert.equal((await db.query(`select count(*)::int n from storage.objects`)).rows[0].n,1);
await db.exec('reset role');await assert.rejects(db.exec(`update private.route_journey_captures set payload='{}' where id='${capture}'`),/immutable/);
await db.exec(`update attendance_verifications set daily_report_id='${report}' where id='${source}'`);await db.exec('set role authenticated');
assert.equal((await db.query(`select public.link_route_journey_report('${report}') n`)).rows[0].n,2);
const evidence=(await db.query(`select public.route_journey_report_evidence('${report}') v`)).rows[0].v;assert.equal(evidence.length,2);assert.equal(evidence[1].payload.captured_address,'実GPS取得住所');
await db.exec(`set test.uid='${other}'`);assert.equal((await db.query(`select public.route_journey_report_evidence('${report}') v`)).rows[0].v.length,0);await db.exec("set test.manage='true'");assert.equal((await db.query(`select public.route_journey_report_evidence('${report}') v`)).rows[0].v.length,2);await db.exec(`set test.uid='${user}'; set test.manage='false'`);
await db.exec('reset role'); await db.exec(`delete from company_members where company_id='${company}' and user_id='${user}'`); await db.exec('set role authenticated');
assert.equal((await db.query('select count(*)::int n from storage.objects')).rows[0].n,0);
await assert.rejects(db.query(`select public.route_journey_workspace('${source}')`),/personal/);
await db.exec('reset role');await db.exec(`insert into company_members values('${company}','${user}','member')`);await db.exec('set role authenticated');
await db.exec(`delete from storage.objects where name='${path}'`);assert.equal((await db.query('select count(*)::int n from storage.objects')).rows[0].n,1);await db.exec(`update storage.objects set name='changed' where name='${path}'`);assert.equal((await db.query(`select name from storage.objects`)).rows[0].name,path);
await db.exec('reset role');await db.exec(`insert into attendance_verifications values(gen_random_uuid(),'${company}','${worker}',null,'${route}','2026-09-30','clock_out','${source}','${report}','location_photo',1)`);await db.exec('set role authenticated');
assert.equal((await save(capture)).rows[0].v.id,capture);await assert.rejects(save(ids[14],stop2),/closed/);
await db.exec('reset role');await db.exec(`update private.route_journey_rollouts set enabled=false; update daily_reports set status='signed' where id='${report}'`);await db.exec('set role authenticated');await assert.rejects(db.query(`select public.link_route_journey_report('${report}')`),/editable/);assert.equal((await db.query(`select public.route_journey_report_evidence('${report}') v`)).rows[0].v.length,2);
await db.exec('set role anon');await assert.rejects(db.query(`select public.route_journey_capture_exact('${capture}')`),/permission denied/);
await db.close();console.log('PASS route journey: OFF, exact own source/stop, parent work_date, immutable failures/live metadata/origin, fixed-ID retry, scoped bucket/no DELETE, report links/signed guard');
