import fs from 'node:fs';
import assert from 'node:assert/strict';
const {PGlite}=await import(process.argv[2]);
const baseline=fs.readFileSync('tool/verify_expense_personal_submission.mjs','utf8');
const anchor=" console.log('PASS expense personal scope, immutable retry, actor isolation, amount/date validation, incurred month, rejected and retired history; no payroll writes');";
assert.ok(baseline.includes(anchor));
const extra=`
 await db.exec('reset role');
 await db.exec(\`create table payroll_manager_worker_visibility(company_id uuid,worker_id uuid,visible_to_manager boolean);
 create table payroll_statements(id uuid primary key,company_id uuid,worker_id uuid,period_start date,period_end date,workflow_state text,revision integer,net_pay integer);
 create table invoices(id uuid primary key,company_id uuid,customer_id uuid,billing_period_start date,status text,revision integer,finalized_at timestamptz);
 create table payment_certificates(id uuid primary key,company_id uuid,partner_company_id uuid,period_start date,status text,revision integer);
 insert into payroll_statements values('\${id(50)}','\${company}','\${worker}','2026-09-01','2026-09-30','finalized',1,1000);
 insert into payroll_statements values('\${id(51)}','\${company}','\${worker}','2026-09-01','2026-09-30','draft',1,1000);
 insert into invoices values('\${id(52)}','\${company}','\${id(30)}','2026-09-01','draft',1,null);
 insert into payment_certificates values('\${id(53)}','\${company}','\${id(32)}','2026-09-01','draft',1);\`);
 await db.exec(fs.readFileSync('supabase/migrations/20261010141814_expense_document_details.sql','utf8'));
 const read=(kind,n)=>call(\`public.read_expense_document('\${kind}','\${id(n)}')\`);
 await db.exec(\`set role authenticated;set test.actor='\${actor}'\`);
 assert.equal((await read('payroll',51)).claims[0].approval,'rejected');
 assert.equal((await read('payroll',50)).claims.length,0);
 await assert.rejects(read('invoice',52),/access denied/);
 await assert.rejects(read('paymentCertificate',53),/access denied/);
 await db.exec(\`set test.actor='\${other}'\`);
 assert.equal((await read('paymentCertificate',53)).claims.length,0);
 await db.exec(\`reset role; update private.expense_claims set allocation='subcontractor',counterparty_id='\${id(32)}',counterparty_name='Partner',approval='approved' where id='\${id(10)}';
 update payroll_statements set workflow_state='finalized' where id='\${id(51)}';
 update payment_certificates set status='finalized' where id='\${id(53)}';
 set role authenticated;\`);
 const frozen=await read('payroll',51);assert.equal(frozen.claims.length,1);assert.equal(frozen.frozen,true);
 const payment=await read('paymentCertificate',53);assert.equal(payment.claims.length,1);
 await db.exec(\`reset role; update private.expense_claims set allocation='customer',counterparty_id='\${id(30)}',counterparty_name='Customer',approval='rejected' where id='\${id(10)}';
 create or replace function private.has_company_feature(uuid,text) returns boolean language sql as $$select true$$;
 set role authenticated;\`);
 assert.deepEqual(await read('payroll',51),frozen);assert.deepEqual(await read('paymentCertificate',53),payment);
 assert.equal((await read('invoice',52)).claims[0].approval,'rejected');
 await db.exec(\`reset role; update invoices set status='finalized' where id='\${id(52)}';set role authenticated;\`);
 const invoice=await read('invoice',52);assert.equal(invoice.frozen,true);
 await db.exec(\`reset role;update private.expense_claims set description='later edit';update payroll_statements set net_pay=1000 where id='\${id(50)}';set role authenticated;\`);
 assert.deepEqual(await read('invoice',52),invoice);assert.equal((await read('payroll',50)).claims.length,0);
 await db.exec(\`set test.actor='\${id(99)}'\`);await assert.rejects(read('payroll',51),/access denied/);
 await db.exec(\`set test.actor='\${actor}';set test.blocked='true'\`);await assert.rejects(read('payroll',51),/unavailable/);
 console.log('PASS expense document scope, rejected payroll history, destination IDs, draft updates, immutable final details, legacy preservation and unchanged payroll amount');
`;
// Keep template interpolation inside the fixture, not the generator.
const body=baseline.slice(baseline.indexOf('const db=')) .replace(anchor,()=>extra.replaceAll('\\`','`'));
await new (Object.getPrototypeOf(async function(){}).constructor)('fs','assert','PGlite',body)(fs,assert,PGlite);
