import fs from 'node:fs';
import assert from 'node:assert/strict';
const {PGlite}=await import(process.argv[2]);
const baseline=fs.readFileSync('tool/verify_expense_review_allocation.mjs','utf8');
const anchor=" console.log('PASS expense-specific assignees, approve to own company, allocation, rejected details, fixed command retries, version conflicts and unchanged other-page assignees');";
const extra=String.raw`
 await db.exec('reset role;set test.blocked=false');
 await db.exec(fs.readFileSync('supabase/migrations/20261010152829_expense_personal_revision.sql','utf8'));
 await db.exec(\`update workers set status='active' where id='\${worker}';set role authenticated;set test.actor='\${actor}'\`);
 const change=(n,rev,action='edit',amount=9876)=>call(\`public.expense_personal_change('\${id(n)}','\${id(10)}',\${rev},'\${action}',\${action==='edit'?"'2026-10-01','養生テープ3巻',"+amount:'null,null,null'})\`);
 const receipt=await call(\`public.expense_personal_exact('\${id(10)}')\`);
 const allocatedAgain=await command(70,7,'allocate','customer',id(30));
 const changed=await change(71,8);assert.equal(changed.approval,'pending');assert.equal(changed.revision,9);assert.equal(changed.allocation,'unallocated');assert.equal(changed.counterparty_id,null);assert.equal(changed.amount_yen,9876);
 assert.deepEqual(await change(71,8),changed,'fixed retry returns original result');
 await assert.rejects(change(71,8,'edit',9877),/fixed personal command differs/);
 await assert.rejects(change(72,8),/changed; reload/);
 assert.equal((await call(\`public.expense_personal_history('\${company}','\${worker}','2026-09-01')\`)).length,0);
 assert.equal((await call(\`public.expense_personal_history('\${company}','\${worker}','2026-10-01')\`))[0].amount_yen,9876);
 assert.equal((await call(\`public.expense_personal_exact('\${id(10)}')\`)).amount_yen,receipt.amount_yen,'original submission remains recoverable');
 assert.equal((await submit(10)).amount_yen,receipt.amount_yen,'direct original submission retry remains recoverable');
 await db.exec(\`set test.actor='\${other}'\`);await assert.rejects(change(73,9),/own expense/);
 await db.exec(\`set test.actor='\${actor}'\`);await assert.rejects(command(73,8,'approve'),/changed; reload/);
 const again=await command(73,9,'approve');assert.equal(again.approval,'approved');assert.equal(again.allocation,'ownCompany');
 assert.deepEqual(await change(71,8),changed,'late retry cannot undo reapproval');
 const withdrawn=await change(74,10,'withdraw');assert.equal(withdrawn.withdrawn,true);assert.equal(withdrawn.revision,11);assert.equal(withdrawn.approval,'rejected');assert.equal(withdrawn.allocation,'unallocated');
 assert.deepEqual(await change(74,10,'withdraw'),withdrawn);
 await assert.rejects(change(75,11),/withdrawn expense/);await assert.rejects(command(75,11,'approve'),/withdrawn expense/);
 await db.exec('reset role');const audit=(await db.query('select before_row,result from private.expense_personal_changes order by created_at')).rows;
 assert.equal(audit.length,2);assert.equal(audit[0].before_row.approval,'approved');assert.equal(audit[0].before_row.counterparty_id,id(30));assert.equal(audit[1].result.withdrawn,true);
 await db.exec('set role authenticated');await assert.rejects(db.query('select * from private.expense_personal_changes'),/permission denied/);
 await db.exec('set role anon');await assert.rejects(change(76,11),/permission denied/);
 console.log('PASS expense personal revision: own-only edits, reapproval, cleared allocation, version conflicts, fixed retry after reapproval, immutable original receipts and retained withdrawal history');
`;
assert.ok(baseline.includes(anchor));
const source=baseline.replace(anchor,()=>extra).replace("import fs from 'node:fs';",'').replace("import assert from 'node:assert/strict';",'').replace('const {PGlite}=await import(process.argv[2]);','');
await new (Object.getPrototypeOf(async function(){}).constructor)('fs','assert','PGlite',source)(fs,assert,PGlite);
