import fs from'node:fs';import assert from'node:assert/strict';
const{PGlite}=await import(process.argv[2]);const db=new PGlite();const readFile=p=>fs.readFileSync(p,'utf8');
const company='10000000-0000-0000-0000-000000000001',other='20000000-0000-0000-0000-000000000001',owner='10000000-0000-0000-0000-000000000011',admin='10000000-0000-0000-0000-000000000012',viewer='10000000-0000-0000-0000-000000000014',worker='10000000-0000-0000-0000-000000000013',otherViewer='20000000-0000-0000-0000-000000000014',fallback='10000000-0000-0000-0000-000000000016',id='30000000-0000-0000-0000-000000000001',oldId='30000000-0000-0000-0000-000000000002',orphanId='30000000-0000-0000-0000-000000000003',hash='a'.repeat(64),bucket='company-income-tax-tables';
const path=`${company}/${id}/1/${hash}.pdf`,revised=`${company}/${id}/2/${hash}.pdf`,oldPath=`${company}/${oldId}/1/${hash}.pdf`,orphan=`${company}/${orphanId}/1/${hash}.pdf`,foreign=`${other}/${id}/1/${hash}.pdf`;
const value={calendar_year:2030,kind:'monthly',starts_on:'2030-01-01',ends_before:'2031-01-01',document_hash:hash,storage_path:path,source_url:'https://example.test/fixture.pdf',publisher:'Fixture only',file_name:'fixture.pdf'};
async function actor(id,operation='object.get_authenticated',role='authenticated',allowed=true){await db.exec('reset role');await db.query("select set_config('test.actor',$1,false),set_config('test.account_allowed',$2,false),set_config('storage.operation',$3,false)",[id,String(allowed),operation]);await db.exec(`set role ${role}`);}
async function read(c=company){return(await db.query('select public.read_company_income_tax_tables($1,$2,$3) as result',[c,'2030-06-01','monthly'])).rows[0].result;}
async function objects(name=path){return(await db.query('select * from storage.objects where bucket_id=$1 and name=$2',[bucket,name])).rows;}
async function insert(name){return db.query('insert into storage.objects(bucket_id,name) values($1,$2)',[bucket,name]);}
async function register(version=0,payload=value,target=id){return(await db.query('select public.register_company_income_tax_table($1,$2,$3,$4::jsonb,true) as result',[company,target,version,JSON.stringify(payload)])).rows[0].result;}
try{
 for(const p of['supabase/tests/company_income_tax_table_registry_bootstrap.sql','supabase/tests/company_income_tax_pdf_storage_bootstrap.sql','supabase/migrations/20261009155006_company_income_tax_table_registry.sql','supabase/migrations/20261009155952_company_income_tax_private_pdf_storage.sql','supabase/tests/company_income_tax_viewer_fixture.sql'])await db.exec(readFile(p));
 await actor(admin,'object.upload');await insert(path);await register();await insert(revised);await register(1,{...value,storage_path:revised});await insert(oldPath);await register(0,{...value,calendar_year:2029,starts_on:'2029-01-01',ends_before:'2030-01-01',storage_path:oldPath},oldId);await insert(orphan);
 await db.exec('reset role');await insert(foreign);await db.query('insert into storage.objects values($1,$2)',['other-bucket','legacy-fixture']);
 // A foreign-company history row cannot authorize this company's unregistered object.
 await db.query("insert into income_tax_private.history(company_id,table_id,version,event_type,after_value,actor_id,changed_at) values($1,$2,1,'registration',$3::jsonb,$4,now())",[other,orphanId,JSON.stringify({...value,storage_path:orphan}),'20000000-0000-0000-0000-000000000012']);
 // Explicit trusted fixture row; upload/registration alone never creates verification.
 await db.query('insert into income_tax_private.verifications values($1,$2,2,$3,$4,$5,now(),$6,$7,$8,$5,now())',[company,id,hash,revised,admin,'Synthetic trusted fixture evidence','b'.repeat(64),'fixture-rules']);
 await actor(admin);const before=await read();assert.equal(before.selected.table_id,id);assert.equal(before.tables.length,2);assert.equal(before.selected.common_data_approved,false);
 await db.exec('reset role');const writesBefore=(await db.query("select proname,md5(prosrc) as hash,proacl from pg_proc where pronamespace='income_tax_private'::regnamespace and proname in ('require_admin','register_document','pdf_object_access') order by proname")).rows;
 const writePoliciesBefore=(await db.query("select polname,polpermissive,polroles,pg_get_expr(polqual,polrelid) as using_expr,pg_get_expr(polwithcheck,polrelid) as check_expr from pg_policy where polrelid='storage.objects'::regclass and polname not in ('income_tax_pdf_read','income_tax_pdf_read_guard') order by polname")).rows;
 const original=(await db.query("select pg_get_functiondef('income_tax_private.read_documents(uuid,text,text)'::regprocedure) as definition")).rows[0].definition;
 await db.exec("create or replace function income_tax_private.read_documents(p_company_id uuid,p_payroll_date text,p_kind text) returns jsonb language plpgsql security definer set search_path='' as $$begin return '{}';end$$");await assert.rejects(db.exec(readFile('supabase/migrations/20261009184013_company_income_tax_viewer_read.sql')),/prerequisite differs/);assert.equal((await db.query("select to_regprocedure('income_tax_private.require_reader(uuid)') as fn")).rows[0].fn,null);await db.exec(original);
 await db.exec(readFile('supabase/migrations/20261009184013_company_income_tax_viewer_read.sql'));
 assert.deepEqual((await db.query("select proname,md5(prosrc) as hash,proacl from pg_proc where pronamespace='income_tax_private'::regnamespace and proname in ('require_admin','register_document','pdf_object_access') order by proname")).rows,writesBefore);
 assert.deepEqual((await db.query("select polname,polpermissive,polroles,pg_get_expr(polqual,polrelid) as using_expr,pg_get_expr(polwithcheck,polrelid) as check_expr from pg_policy where polrelid='storage.objects'::regclass and polname not in ('income_tax_pdf_read','income_tax_pdf_read_guard') order by polname")).rows,writePoliciesBefore);
 await actor(admin);assert.deepEqual(await read(),{...before,can_edit:true});assert.equal((await objects(orphan)).length,1,'existing admin orphan read remains');await actor(owner);assert.deepEqual(await read(),{...before,can_edit:true});
 await actor(viewer);const visible=await read();assert.equal(visible.can_edit,false);assert.deepEqual(visible.history,[]);assert.deepEqual(visible.tables,before.tables.map(({registered_by,...row})=>row));const{registered_by,...selected}=before.selected;assert.deepEqual(visible.selected,selected);
 for(const operation of['object.get_authenticated','storage.object.get_authenticated','object.get_authenticated_info','object.head_authenticated_info','object.sign']){await actor(viewer,operation);for(const name of[path,revised,oldPath])assert.equal((await objects(name)).length,1);assert.equal((await objects(orphan)).length,0);assert.equal((await objects(foreign)).length,0);}
 for(const operation of['','object.list','object.list_v2','object.sign_many','object.get_signed','object.upload','object.upload_update']){await actor(viewer,operation);assert.equal((await objects(revised)).length,0,operation);}
 await actor(viewer,'object.upload');await assert.rejects(insert(`${company}/${orphanId}/2/${hash}.pdf`),/row-level security/);await assert.rejects(register(2,{...value,storage_path:revised}),/admin access denied/);
 await actor(viewer,'object.sign');assert.equal((await db.query('update storage.objects set name=name where bucket_id=$1 and name=$2 returning name',[bucket,revised])).rows.length,0);assert.equal((await db.query('delete from storage.objects where bucket_id=$1 and name=$2 returning name',[bucket,revised])).rows.length,0);
 await assert.rejects(db.query('select * from income_tax_private.history'),/permission denied/);await assert.rejects(db.query('insert into income_tax_private.verifications(company_id) values($1)',[company]),/permission denied/);
 for(const bad of['not-a-path',path.replace('/1/','/0/'),path.replace('/1/','/9999999999999999999/'),path.replace(hash,'fake')])assert.equal((await db.query('select income_tax_private.pdf_object_read_access($1) as allowed',[bad])).rows[0].allowed,false);
 for(const who of[worker,otherViewer,fallback,'']){await actor(who);await assert.rejects(read(),/reader access denied/);assert.equal((await objects(revised)).length,0);}
 await actor(viewer,'object.sign','authenticated',false);await assert.rejects(read(),/reader access denied/);assert.equal((await objects(revised)).length,0);
 await actor(viewer,'object.sign','anon');await assert.rejects(read(),/permission denied/);assert.equal((await objects(revised)).length,0);
 await actor(viewer);assert.equal((await db.query("select * from storage.objects where bucket_id='other-bucket' and name='legacy-fixture'")).rows.length,1,'other bucket policy unchanged');
 await actor(admin,'object.upload');const third=`${company}/${id}/3/${hash}.pdf`;await insert(third);const newlyUploaded=await register(2,{...value,storage_path:third});assert.equal(newlyUploaded.official_document_verified,false);assert.equal(newlyUploaded.calculation_rules_verified,false);assert.equal(newlyUploaded.common_data_approved,false);
 await actor(viewer,'object.sign');assert.equal((await read()).selected,null);assert.equal((await objects(third)).length,1);assert.equal((await objects(revised)).length,1,'prior registered version remains readable');
 await db.exec('reset role');await db.query('delete from public.companies where id=$1',[company]);
 assert.ok((await db.query('select count(*)::int as n from income_tax_private.history where company_id=$1',[company])).rows[0].n>0);
 for(const who of[admin,viewer]){await actor(who);await assert.rejects(read(),/reader access denied/);assert.equal((await objects(revised)).length,0);assert.equal((await objects(path)).length,0);}
 console.log('PASS income viewer metadata capability/projection; same-company registered current/history PDF get/sign; orphan/cross-company/list/upload/update/delete/anon denial; unchanged admin writes/access and deleted-company guard');
}catch(e){console.error(e.message,e.where||'');process.exitCode=1;}finally{await db.close();}
