import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const {PGlite}=await import(process.argv[2]);
const db=new PGlite();
await db.exec(await fs.readFile(new URL('./fixtures/route_journey_capture/schema.sql',import.meta.url),'utf8'));
await db.exec(await fs.readFile(new URL('../supabase/migrations/20261008204012_route_journey_capture_staged.sql',import.meta.url),'utf8'));
await db.exec(await fs.readFile(new URL('../supabase/migrations/20261010132957_route_journey_visit_lifecycle.sql',import.meta.url),'utf8'));
await db.exec(await fs.readFile(new URL('../supabase/migrations/20261010222139_route_manual_visit_capture.sql',import.meta.url),'utf8'));
const ids=Array.from({length:15},(_,i)=>`00000000-0000-0000-0000-${String(i+1).padStart(12,'0')}`);
const [company,user,other,worker,route,stop,source,report,capture,stop2,capture2,foreignCompany,foreignWorker,foreignSource,foreignStop]=ids;
await db.exec(`set test.uid='${user}'; insert into companies values('${company}'),('${foreignCompany}'); insert into company_members values('${company}','${user}','member'),('${company}','${other}','member'); insert into workers values('${worker}','${company}','${user}','本人','active'),('${foreignWorker}','${foreignCompany}','${other}','別会社','active'); insert into route_assignments values('${route}','${company}'); insert into route_stops values('${stop}','${route}',null,1,'計画住所','現場1'),('${stop2}','${route}',null,2,'計画住所2','現場2'),('${foreignStop}',gen_random_uuid(),null,1,'別のルート','別'); insert into attendance_verifications values('${source}','${company}','${worker}',null,'${route}','2026-09-30','clock_in',null,null,'location_photo',1),('${foreignSource}','${foreignCompany}','${foreignWorker}',null,'${route}','2026-09-30','clock_in',null,null,'location_photo',1); insert into daily_reports values('${report}','${company}',null,'${route}','2026-09-30','${user}','draft'); insert into daily_report_workers values('${report}','${worker}');`);
const json = value => `'${JSON.stringify(value).replaceAll("'","''")}'::jsonb`;
const failure={capture_contract_version:1,gps_capture_status:'failed',photo_capture_status:'failed',gps_captured_at:null,photo_captured_at:null,photo_observed_at:null,captured_address:null,latitude:null,longitude:null,accuracy_m:null,photo_storage_path:null,attempted_at:'2026-10-01T00:01:00Z'};
const save=(id,stopId=stop,payload=failure,origin='company',sourceId=source)=>db.query(`select public.save_route_journey_capture('${id}','${sourceId}','${stopId}','${origin}',${json(payload)}) v`);
const uuid = n => `10000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
const visit=(id,kind='start',startId=id,stopId=stop,sourceId=source,eventPayload=failure)=>db.query(`select public.save_route_journey_visit('${id}','${sourceId}','${stopId}','company',${json(eventPayload)},'${kind}','${startId}') v`);
const ws=async()=> (await db.query(`select public.route_journey_visit_workspace('${source}') v`)).rows[0].v;
const clockOut=()=>db.exec(`insert into attendance_verifications values('${uuid(90)}','${company}','${worker}',null,'${route}','2026-09-30','clock_out','${source}',null,'location_photo',1)`);
await db.exec('set role authenticated');
assert.equal((await ws()).enabled,false);
await assert.rejects(visit(uuid(1)),/disabled/);
await db.exec('reset role');await db.exec(`insert into private.route_journey_rollouts values('${company}',true)`);await db.exec('set role authenticated');
const first=(await visit(uuid(1))).rows[0].v;
assert.equal(first.visit_kind,'start');assert.equal(first.start_capture_id,uuid(1));assert.equal(first.work_date,'2026-09-30');
assert.deepEqual((await visit(uuid(1))).rows[0].v,first);
assert.equal((await ws()).visits.length,1);assert.equal((await ws()).visits[0].ended_at,null);
await assert.rejects(visit(uuid(2)),/finish current/);
await assert.rejects(visit(uuid(3),'end',uuid(9)),/selected open/);
await assert.rejects(visit(uuid(3),'end',uuid(1),stop2),/selected open/);
await assert.rejects(visit(uuid(1),'end',uuid(9)),/mismatch/);
await db.exec('reset role');await assert.rejects(clockOut(),/finish current visit/);
assert.equal((await db.query('select count(*)::int n from private.route_journey_captures')).rows[0].n,1);
await db.exec('set role authenticated');
await db.exec(`set test.uid='${other}'`);await assert.rejects(visit(uuid(3),'end',uuid(1)),/personal/);
assert.equal((await db.query(`select public.route_journey_visit_exact('${uuid(1)}') v`)).rows[0].v,null);
await db.exec(`set test.uid='${user}'`);
const ended=(await visit(uuid(3),'end',uuid(1))).rows[0].v;
assert.equal(ended.visit_kind,'end');assert.equal((await ws()).is_open,true);
assert.notEqual((await ws()).visits[0].ended_at,null);
await assert.rejects(visit(uuid(4),'end',uuid(1)),/selected open/);
await visit(uuid(5),'start',uuid(5),stop2);
await visit(uuid(6),'end',uuid(5),stop2);
const visits=(await ws()).visits;
assert.equal(visits.length,2);assert.equal(visits[1].route_stop_id,stop2);
assert.ok(visits.every(v=>v.work_date==='2026-09-30'));
// Manual shifts reuse the lifecycle, keeping time-only evidence and exact retries.
const manualSource=uuid(100), manualStart=uuid(101), manualEnd=uuid(102);
await db.exec('reset role');
await db.exec(`insert into attendance_verifications values('${manualSource}','${company}','${worker}',null,'${route}','2026-09-30','clock_in',null,null,'manual',null)`);
await db.exec('set role authenticated');
const manualWorkspace=(await db.query(`select public.route_journey_visit_workspace('${manualSource}') v`)).rows[0].v;
assert.equal(manualWorkspace.enabled,true);assert.equal(manualWorkspace.verification_mode,'manual');
await assert.rejects(visit(manualStart,'start',manualStart,stop,manualSource),/time only/);
const timeOnly={...failure,gps_capture_status:'missing',photo_capture_status:'missing'};
const manualSaved=(await visit(manualStart,'start',manualStart,stop,manualSource,timeOnly)).rows[0].v;
assert.deepEqual((await visit(manualStart,'start',manualStart,stop,manualSource,timeOnly)).rows[0].v,manualSaved);
await visit(manualEnd,'end',manualStart,stop,manualSource,{...timeOnly,attempted_at:'2026-10-01T00:02:00Z'});
const manualVisit=(await db.query(`select public.route_journey_visit_workspace('${manualSource}') v`)).rows[0].v.visits[0];
assert.equal(Date.parse(manualVisit.started_at),Date.parse(timeOnly.attempted_at));
assert.equal(Date.parse(manualVisit.ended_at),Date.parse('2026-10-01T00:02:00Z'));
await db.exec('reset role');
await db.exec(`update attendance_verifications set daily_report_id='${report}' where id='${manualSource}'`);
await db.exec('set role authenticated');
await db.query(`select public.link_route_journey_report('${report}')`);
const manualEvidence=(await db.query(`select public.route_journey_report_evidence('${report}') v`)).rows[0].v.filter(r=>r.source_clock_in_id===manualSource);
assert.deepEqual(manualEvidence.map(r=>r.visit_kind).sort(),['end','start']);
assert.ok(manualEvidence.every(r=>r.verification_mode==='manual'&&r.start_capture_id===manualStart));
await db.exec('reset role');await db.exec(`delete from attendance_verifications where id='${manualSource}'`);await db.exec('set role authenticated');
// A legacy GPS capture is not guessed to be a visit start/end.
await save(capture);await assert.rejects(visit(capture),/legacy capture/);
await db.exec('reset role');await clockOut();
await db.exec(`update private.route_journey_rollouts set enabled=false`);await db.exec('set role authenticated');
assert.deepEqual((await visit(uuid(3),'end',uuid(1))).rows[0].v,ended);
assert.equal((await db.query(`select public.route_journey_visit_exact('${uuid(3)}') v`)).rows[0].v.visit_kind,'end');
await assert.rejects(visit(uuid(7)),/disabled|closed/);
await assert.rejects(db.query('select * from private.route_journey_visit_events'),/permission denied/);
await db.exec('begin isolation level repeatable read');await assert.rejects(visit(uuid(8)),/read committed/);await db.exec('rollback');
// Original raw capture, visit link and source survive management-style cascade.
await db.exec('reset role');
await db.exec(`update attendance_verifications set daily_report_id='${report}' where id='${source}';update private.route_journey_captures set daily_report_id='${report}' where source_clock_in_id='${source}'`);
const reportBefore=(await db.query(`select to_jsonb(d) v from daily_reports d where id='${report}'`)).rows[0].v;
const before=(await db.query(`select to_jsonb(c) v from private.route_journey_captures c where id='${uuid(1)}'`)).rows[0].v;
await db.exec(`delete from daily_reports where id='${report}'`);
assert.deepEqual((await db.query(`select report_snapshot v from private.route_journey_visit_archive where id='${uuid(1)}'`)).rows[0].v,reportBefore);
assert.equal((await db.query(`select daily_report_id from private.route_journey_captures where id='${uuid(1)}'`)).rows[0].daily_report_id,null);
await db.exec(`delete from attendance_verifications where id='${source}'`);
assert.equal((await db.query('select count(*)::int n from private.route_journey_visit_events')).rows[0].n,0);
const archived=(await db.query(`select * from private.route_journey_visit_archive where id='${uuid(1)}'`)).rows[0];
assert.deepEqual(archived.raw_capture,before);assert.equal(archived.visit_event.kind,'start');assert.equal(archived.source_snapshot.id,source);
await db.exec('set role authenticated');
const recovered=(await db.query(`select public.route_journey_visit_exact('${uuid(1)}') v`)).rows[0].v;
assert.equal(recovered.archived,true);assert.equal(recovered.visit_kind,'start');assert.deepEqual(recovered.payload,before.payload);
const archivedWs=await ws();assert.equal(archivedWs.archived,true);assert.equal(archivedWs.enabled,false);assert.equal(archivedWs.is_open,false);
await db.exec(`set test.uid='${other}'`);
assert.equal((await db.query(`select public.route_journey_visit_exact('${uuid(1)}') v`)).rows[0].v,null);
await assert.rejects(db.query(`select public.route_journey_visit_workspace('${source}')`),/personal/);
await db.exec(`set test.uid='${user}'`);
await assert.rejects(db.query('select * from private.route_journey_visit_archive'),/permission denied/);
await db.exec('reset role');
await assert.rejects(db.exec(`insert into attendance_verifications values('${source}','${company}','${worker}',null,'${route}','2026-09-30','clock_in',null,null,'location_photo',1)`),/archived route identity/);
// If archiving fails, the management delete and child cascade roll back.
await db.exec(`update private.route_journey_rollouts set enabled=true;
 insert into attendance_verifications values('${uuid(73)}','${company}','${worker}',null,'${route}','2026-09-30','clock_in',null,null,'location_photo',1)`);
const retainedPath=`${company}/attendance/${route}/${worker}/${uuid(73)}/retained.jpg`;
await db.exec(`insert into storage.objects(bucket_id,name) values('attendance-route-evidence','${retainedPath}')`);
await db.exec('set role authenticated');await visit(uuid(74),'start',uuid(74),stop,uuid(73),{...failure,photo_capture_status:'uploaded',photo_storage_path:retainedPath,photo_observed_at:'2026-10-01T00:01:00Z'});await db.exec('reset role');
await db.exec(`create function private.test_archive_fail() returns trigger language plpgsql as $$begin raise exception 'test archive unavailable';end$$;
 create trigger test_archive_fail before insert on private.route_journey_visit_archive for each row execute function private.test_archive_fail()`);
await assert.rejects(db.exec(`delete from attendance_verifications where id='${uuid(73)}'`),/test archive unavailable/);
assert.equal((await db.query(`select count(*)::int n from private.route_journey_captures where id='${uuid(74)}'`)).rows[0].n,1);
assert.equal((await db.query(`select count(*)::int n from attendance_verifications where id='${uuid(73)}'`)).rows[0].n,1);
await db.exec('drop trigger test_archive_fail on private.route_journey_visit_archive');
const parentPath=`${company}/attendance/${route}/${worker}/parent.jpg`;
await db.exec(`alter table attendance_verifications add column photo_storage_path text;
 update attendance_verifications set photo_storage_path='${parentPath}' where id='${uuid(73)}';
 insert into storage.objects(bucket_id,name) values('attendance-evidence','${parentPath}'),('attendance-evidence','orphan');
 create policy test_manager_read on storage.objects for select to authenticated using(true);
 create policy test_manager_delete on storage.objects for delete to authenticated using(true);
 create policy test_manager_update on storage.objects for update to authenticated using(true) with check(true)`);
await db.exec('set role authenticated');
assert.equal((await db.query(`delete from storage.objects where name='${parentPath}' returning name`)).rows.length,0);
await db.exec('reset role');await db.exec(`delete from attendance_verifications where id='${uuid(73)}'`);await db.exec('set role authenticated');
for(const path of [parentPath,retainedPath]) {
 assert.equal((await db.query(`delete from storage.objects where name='${path}' returning name`)).rows.length,0);
 assert.equal((await db.query(`update storage.objects set name='replacement' where name='${path}' returning name`)).rows.length,0);
}
assert.equal((await db.query(`delete from storage.objects where name='orphan' returning name`)).rows.length,1);
console.log('PASS retention: parent/report cascade, original visit/source/report, scoped archived retry, UUID tombstone, rollback on archive failure, restrictive DELETE/UPDATE with permissive manager policies');
await db.exec('set role anon');await assert.rejects(db.query(`select public.route_journey_visit_workspace('${source}')`),/permission denied/);
await db.close();console.log('PASS visits: OFF, personal source, two visits, midnight source date, exact retries, atomic rejection, end != clock-out, unfinished clock-out rejection, legacy isolation');
