// Synthetic fixture only; never opens a production connection or reads real photos.
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
const {PGlite}=await import(pathToFileURL(process.argv[2]).href);
const db=new PGlite();
const sql=async p=>db.exec(await fs.readFile(new URL('../'+p,import.meta.url),'utf8'));
await sql('tool/fixtures/qualification_photo_submission/schema.sql');
await sql('tool/fixtures/qualification_photo_submission/live_functions.sql');
await db.exec(`revoke all on function private.personal_qualification_submission(text,jsonb),private.qualification_submission_access(text,boolean) from public,anon;grant execute on function private.personal_qualification_submission(text,jsonb),private.qualification_submission_access(text,boolean) to authenticated;
 create policy submission_upload on storage.objects for insert to authenticated with check(bucket_id='qualification-certificates' and private.qualification_submission_access(name,true));
 create policy submission_read on storage.objects for select to authenticated using(bucket_id='qualification-certificates' and private.qualification_submission_access(name,false));`);
await sql('supabase/migrations/20261010222157_add_qualification_certificate_extra_photos.sql');
await sql('supabase/migrations/20261010222753_protect_qualification_photo_snapshots.sql');
const ids=Array.from({length:12},(_,i)=>`10000000-0000-0000-0000-${String(i+1).padStart(12,'0')}`);
const [company,user,reviewer,other,worker,master,target,request,request2,request3,request4,foreignCompany]=ids;
const oldFront=`${company}/${worker}/${master}/legacy-request/submission.pdf`;
const oldBack=`${company}/${worker}/${master}/legacy-request/back.jpg`;
await db.exec(`insert into companies values('${company}'),('${foreignCompany}');
 insert into company_members values('${company}','${user}','member'),('${company}','${reviewer}','admin'),('${company}','${other}','member');
 insert into workers(id,company_id,user_id) values('${worker}','${company}','${user}');
 insert into qualification_master values('${master}','${company}','資格',false);
 insert into storage.objects(bucket_id,name) values('qualification-certificates','${oldFront}'),('qualification-certificates','${oldBack}');
 insert into worker_qualifications(id,company_id,worker_id,qualification_master_id,certificate_number,issuer,attachment_path,attachment_back_path,notes)
 values('${target}','${company}','${worker}','${master}','original','issuer','${oldFront}','${oldBack}','unchanged');`);
await sql('supabase/migrations/20261010233011_personal_qualification_photo_submission.sql');
const actor=async uid=>db.exec(`set test.uid='${uid}';set role authenticated`);
const rpc=async(action,data={})=>(await db.query('select private.personal_qualification_submission($1,$2::jsonb) v',[action,JSON.stringify(data)])).rows[0].v;
const prepare=(id,slots,targetId=target)=>rpc('prepare_photos',{request_id:id,target_id:targetId,photo_slots:slots});
await actor(user);
assert.deepEqual(await rpc('photo_capability'),{version:1,photo_submission_available:true,photo_upload_allowed:true,max_photos:20});
await assert.rejects(db.query('select * from private.qualification_submissions'),e=>e.code==='42501');
assert.equal((await db.query("update worker_qualifications set notes='unauthorized' returning id")).rows.length,0);
const slots=[{existing_path:oldBack},{extension:'jpg'},{existing_path:oldFront}];
const prepared=await prepare(request,slots);
assert.equal(prepared.id,request);assert.equal(prepared.requested_by,user);
assert.deepEqual(prepared.photo_paths,[oldBack,`${company}/${worker}/${target}/submissions/${request}-2.jpg`,oldFront]);
assert.deepEqual(prepared.upload_paths,[{index:1,path:prepared.photo_paths[1],extension:'jpg'}]);
assert.deepEqual(await prepare(request,slots),prepared);
await assert.rejects(prepare(request,[]),e=>e.code==='23505');
assert.deepEqual(await rpc('get_photos',{id:request}),prepared);
await assert.rejects(rpc('submit',{id:request}),/添付資格証/);
await db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['qualification-certificates',prepared.photo_paths[1]]);
await assert.rejects(db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['qualification-certificates',prepared.photo_paths[1]]),e=>e.code==='23505');
assert.equal((await db.query('update storage.objects set name=name where name=$1 returning id',[prepared.photo_paths[1]])).rows.length,0);
assert.equal((await rpc('submit',{id:request})).status,'pending');
assert.equal((await rpc('submit',{id:request})).status,'pending');
await assert.rejects(db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['qualification-certificates',`${company}/${worker}/${target}/submissions/unplanned.jpg`]),e=>e.code==='42501');
await actor(other);
await assert.rejects(rpc('get_photos',{id:request}),/確認できません/);
await assert.rejects(prepare(request2,[{existing_path:oldFront}]),/本人/);
await assert.rejects(rpc('approve',{id:request}),/承認権限/);
await assert.rejects(rpc('cancel_photos',{id:request}),/取り消せません/);
await actor(reviewer);
assert.equal((await rpc('get_photos',{id:request})).status,'pending');
assert.equal((await db.query('select name from storage.objects where name=$1',[oldBack])).rows.length,1);
await rpc('approve',{id:request});
assert.equal((await rpc('get_photos',{id:request})).status,'approved');
await db.exec('reset role');
const saved=(await db.query('select * from worker_qualifications where id=$1',[target])).rows[0];
assert.equal(saved.certificate_number,'original');assert.equal(saved.notes,'unchanged');
assert.equal(saved.attachment_path,oldBack);assert.equal(saved.attachment_back_path,prepared.photo_paths[1]);
assert.deepEqual(saved.attachment_extra_paths,[oldFront]);
// Even after approval, pending/terminal submission references prevent overwrites.
await actor(user);assert.equal((await rpc('submit',{id:request})).status,'approved');
const listed=await rpc('list');assert.equal(listed[0].photo_contract_version,1);assert.deepEqual(listed[0].photo_paths,prepared.photo_paths);
await actor(reviewer);assert.equal((await db.query('delete from storage.objects where name=$1 returning id',[oldBack])).rows.length,0);
await actor(user);
await prepare(request2,[{existing_path:oldFront}]);await rpc('submit',{id:request2});
await db.exec('reset role');await db.query("update worker_qualifications set notes='concurrent metadata' where id=$1",[target]);
await actor(reviewer);await assert.rejects(rpc('approve',{id:request2}),/更新されました/);
await rpc('reject',{id:request2,reason:'再申請'});
assert.equal((await rpc('get_photos',{id:request2})).status,'rejected');
await actor(user);assert.equal((await rpc('get_photos',{id:request2})).status,'rejected');
await assert.rejects(rpc('cancel_photos',{id:request2}),/未送信/);
await assert.rejects(rpc('cancel_photos',{id:request}),/未送信/);
const cancelId='20000000-0000-0000-0000-000000000001';
const cancelDraft=await prepare(cancelId,[{existing_path:oldFront},{extension:'jpg'}]);
await db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['qualification-certificates',cancelDraft.upload_paths[0].path]);
await actor(other);await assert.rejects(rpc('cancel_photos',{id:cancelId}),/取り消せません/);
await actor(reviewer);await assert.rejects(rpc('cancel_photos',{id:cancelId}),/取り消せません/);
await actor(user);
const cancelled=await rpc('cancel_photos',{id:cancelId});
assert.equal(cancelled.status,'rejected');assert.equal(cancelled.cancelled,true);
assert.deepEqual(await rpc('cancel_photos',{id:cancelId}),cancelled);
assert.deepEqual(await rpc('get_photos',{id:cancelId}),cancelled);
await actor(reviewer);await assert.rejects(rpc('get_photos',{id:cancelId}),/確認できません/);await actor(user);
await assert.rejects(rpc('submit',{id:cancelId}),/送信できません/);
await db.exec('reset role');
await db.exec("create policy fixture_cleanup on storage.objects for delete to authenticated using(true)");
await actor(user);
for(const retainedPath of [oldFront,cancelDraft.upload_paths[0].path]){
 assert.equal((await db.query('delete from storage.objects where name=$1 returning id',[retainedPath])).rows.length,0);
 assert.equal((await db.query('update storage.objects set name=name where name=$1 returning id',[retainedPath])).rows.length,0);
}
await assert.rejects(db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['qualification-certificates',cancelled.upload_paths[0].path]),e=>e.code==='42501');
// Explicit all-photo removal changes no qualification metadata or saved evidence.
await prepare(request3,[]);await rpc('submit',{id:request3});await actor(reviewer);await rpc('approve',{id:request3});
await db.exec('reset role');
const removed=(await db.query('select attachment_path,attachment_back_path,attachment_extra_paths,notes from worker_qualifications where id=$1',[target])).rows[0];
assert.equal(removed.attachment_path,null);assert.equal(removed.attachment_back_path,null);assert.deepEqual(removed.attachment_extra_paths,[]);assert.equal(removed.notes,'concurrent metadata');
// Reordering owned legacy paths is allowed only on the original qualification.
await assert.rejects(db.query('update worker_qualifications set attachment_extra_paths=$1 where id=$2',[[oldFront],target]),/保存先/);
await actor(user);await assert.rejects(prepare(request4,[{existing_path:oldFront}]),/登録済み写真/);
await assert.rejects(prepare(request4,[{existing_path:'foreign/path'}]),/登録済み写真/);
// Existing restrictive upload pilot is not removed or weakened.
await db.exec('reset role');await db.exec("create policy license_document_pilot_insert_scope on storage.objects as restrictive for insert to authenticated with check(bucket_id='worker-documents')");
await actor(user);assert.equal((await rpc('photo_capability')).photo_upload_allowed,false);
await assert.rejects(prepare(request4,[{extension:'jpg'}]),/停止/);
// Legacy single prepare/submit/approve remains usable with its original path.
await db.exec('reset role');await db.exec('drop policy license_document_pilot_insert_scope on storage.objects');
await actor(user);const legacy=await rpc('prepare',{worker_id:worker,qualification_master_id:master,target_id:target,extension:'jpg',certificate_number:'legacy-number'});
assert.match(legacy.upload_path,new RegExp(`^${company}/${worker}/${master}/`));
await db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['qualification-certificates',legacy.upload_path]);
await rpc('submit',{id:legacy.id});await actor(reviewer);await rpc('approve',{id:legacy.id});
await db.exec('reset role');assert.equal((await db.query('select certificate_number from worker_qualifications where id=$1',[target])).rows[0].certificate_number,'legacy-number');
await actor(user);await assert.rejects(db.query('select private.personal_qualification_photo_submission($1,$2::jsonb)',['photo_capability','{}']),e=>e.code==='42501');
await db.close();console.log('PASS personal qualification photos: fixed prepare/submit retry, full CAS, scoped approval, canonical upload, legacy reorder/contract, all-photo removal, pilot OFF and retained evidence');
