import fs from 'node:fs';
import assert from 'node:assert/strict';
const {PGlite}=await import(process.argv[2]);
const db=new PGlite();
try {
 await db.exec(`create schema private; create schema auth; create role anon; create role authenticated;
 grant usage on schema private,auth,public to authenticated,anon;
 create function auth.uid() returns uuid language sql as $$select nullif(current_setting('test.actor',true),'')::uuid$$;
 create function private.account_access_allowed() returns boolean language sql as $$select coalesce(current_setting('test.blocked',true),'false') <> 'true'$$;
 create function private.has_company_feature(uuid,text) returns boolean language sql as $$select false$$;
 create table companies(id uuid primary key,name text);
 create table workers(id uuid primary key,company_id uuid,user_id uuid,name text,status text);
 create table company_members(company_id uuid,user_id uuid,role text);`);
 await db.exec(fs.readFileSync('supabase/migrations/20261010044054_expense_personal_submission.sql','utf8'));
 const id=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
 const [company,actor,worker,other,otherWorker,foreignCompany]=[1,2,3,4,5,6].map(id);
 await db.exec(`insert into companies values('${company}','Company'),('${foreignCompany}','Other');
 insert into company_members values('${company}','${actor}','viewer'),('${company}','${other}','admin');
 insert into workers values('${worker}','${company}','${actor}','本人','active'),('${otherWorker}','${company}','${other}','別人','active');
 set role authenticated;set test.actor='${actor}';`);
 const call=async sql=>(await db.query(`select ${sql} v`)).rows[0].v;
 const submit=(n,extra={})=>call(`public.expense_personal_submit('${id(n)}','${extra.company??company}','${extra.worker??worker}','${extra.date??'2026-09-30'}','${extra.description??'交通費'}',${extra.amount??1234})`);
 const first=await submit(10);assert.equal(first.approval,'pending');assert.equal(first.allocation,'unallocated');assert.equal(first.created_by,actor);
 assert.deepEqual(await submit(10),first);
 for(const extra of [{amount:1235},{date:'2026-09-29'},{description:'別の経費'}])await assert.rejects(submit(10,extra),/fixed expense differs/);
 await assert.rejects(submit(11,{worker:otherWorker}),/own worker required/);
 await assert.rejects(submit(11,{company:foreignCompany}),/unavailable/);
 for(const extra of [{amount:0},{amount:-1},{amount:1000000000},{description:' '},{date:'2999-01-01'}])await assert.rejects(submit(11,extra),/invalid expense/);
 assert.equal((await call(`public.expense_personal_scopes()`)).length,1);
 assert.equal((await call(`public.expense_personal_history('${company}','${worker}','2026-09-01')`)).length,1);
 assert.equal((await call(`public.expense_personal_history('${company}','${worker}','2026-10-01')`)).length,0);
 await assert.rejects(call(`public.expense_personal_history('${company}','${otherWorker}','2026-09-01')`),/unavailable/);
 await db.exec(`set test.actor='${other}'`);
 assert.equal(await call(`public.expense_personal_exact('${id(10)}')`),null);
 await assert.rejects(call(`public.expense_personal_history('${company}','${worker}','2026-09-01')`),/unavailable/);
 await db.exec(`set test.actor='${actor}';set test.blocked='true'`);
 await assert.rejects(submit(11),/unavailable/);
 await assert.rejects(call(`public.expense_personal_exact('${id(10)}')`),/unavailable/);
 await db.exec(`set test.blocked='false';reset role;update private.expense_claims set approval='rejected' where id='${id(10)}';update workers set status='retired' where id='${worker}';set role authenticated;`);
 assert.equal((await submit(10)).approval,'rejected');
 assert.equal((await call(`public.expense_personal_history('${company}','${worker}','2026-09-01')`))[0].approval,'rejected');
 await assert.rejects(submit(12),/active worker required/);
 await assert.rejects(db.query('select * from private.expense_claims'),/permission denied/);
 await db.exec('set role anon');await assert.rejects(call('public.expense_personal_scopes()'),/permission denied/);
 console.log('PASS expense personal scope, immutable retry, actor isolation, amount/date validation, incurred month, rejected and retired history; no payroll writes');
} finally {await db.close();}
