import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const {PGlite}=await import(process.argv[2]);
const db=new PGlite();
await db.exec(await fs.readFile(new URL('./fixtures/route_journey_capture/schema.sql',import.meta.url),'utf8'));
await db.exec(await fs.readFile(new URL('../supabase/migrations/20261008204012_route_journey_capture_staged.sql',import.meta.url),'utf8'));
await db.exec(await fs.readFile(new URL('./fixtures/route_journey_visits/visits.sql',import.meta.url),'utf8'));
const ids=Array.from({length:15},(_,i)=>`00000000-0000-0000-0000-${String(i+1).padStart(12,'0')}`);
const [company,user,other,worker,route,stop,source,report,capture,stop2,capture2,foreignCompany,foreignWorker,foreignSource,foreignStop]=ids;
await db.exec(`set test.uid='${user}'; insert into companies values('${company}'),('${foreignCompany}'); insert into company_members values('${company}','${user}','member'),('${company}','${other}','member'); insert into workers values('${worker}','${company}','${user}','本人','active'),('${foreignWorker}','${foreignCompany}','${other}','別会社','active'); insert into route_assignments values('${route}','${company}'); insert into route_stops values('${stop}','${route}',null,1,'計画住所','現場1'),('${stop2}','${route}',null,2,'計画住所2','現場2'),('${foreignStop}',gen_random_uuid(),null,1,'別のルート','別'); insert into attendance_verifications values('${source}','${company}','${worker}',null,'${route}','2026-09-30','clock_in',null,null,'location_photo',1),('${foreignSource}','${foreignCompany}','${foreignWorker}',null,'${route}','2026-09-30','clock_in',null,null,'location_photo',1); insert into daily_reports values('${report}','${company}',null,'${route}','2026-09-30','${user}','draft'); insert into daily_report_workers values('${report}','${worker}');`);
const json = value => `'${JSON.stringify(value).replaceAll("'","''")}'::jsonb`;
const failure={capture_contract_version:1,gps_capture_status:'failed',photo_capture_status:'failed',gps_captured_at:null,photo_captured_at:null,photo_observed_at:null,captured_address:null,latitude:null,longitude:null,accuracy_m:null,photo_storage_path:null,attempted_at:'2026-10-01T00:01:00Z'};
const save=(id,stopId=stop,payload=failure,origin='company',sourceId=source)=>db.query(`select public.save_route_journey_capture('${id}','${sourceId}','${stopId}','${origin}',${json(payload)}) v`);
const uuid = n => `10000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
const visit=(id,kind='start',startId=id,stopId=stop,sourceId=source)=>db.query(`select public.save_route_journey_visit('${id}','${sourceId}','${stopId}','company',${json(failure)},'${kind}','${startId}') v`);
const ws=async()=> (await db.query(`select public.route_journey_visit_workspace('${source}') v`)).rows[0].v;
const clockOut=()=>db.exec(`insert into attendance_verifications values('${uuid(90)}','${company}','${worker}',null,'${route}','2026-09-30','clock_out','${source}',null,'location_photo',1)`);
await db.exec('set role authenticated');
assert.equal((await ws()).enabled,false);
await assert.rejects(visit(uuid(1)),/disabled/);
await db.exec('reset role');await db.exec(`insert into private.route_journey_rollouts values('${company}',true)`);await db.exec('set role authenticated');
const first=(await visit(uuid(1))).rows[0].v;
assert.equal(first.visit_kind,'start');assert.equal(first.start_capture_id,uuid(1));assert.equal(first.work_date,'2026-09-30');
assert.deepEqual((await visit(uuid(1))).rows[0].v,first);
assert.equal((await ws()).visits.length,1);assert.equal((await ws()).visits[0].ended_at,null);
await assert.rejects(visit(uuid(2)),/finish current/);
await assert.rejects(visit(uuid(3),'end',uuid(9)),/selected open/);
await assert.rejects(visit(uuid(3),'end',uuid(1),stop2),/selected open/);
await assert.rejects(visit(uuid(1),'end',uuid(9)),/mismatch/);
await db.exec('reset role');await assert.rejects(clockOut(),/finish current visit/);
assert.equal((await db.query('select count(*)::int n from private.route_journey_captures')).rows[0].n,1);
await db.exec('set role authenticated');
await db.exec(`set test.uid='${other}'`);await assert.rejects(visit(uuid(3),'end',uuid(1)),/personal/);
assert.equal((await db.query(`select public.route_journey_visit_exact('${uuid(1)}') v`)).rows[0].v,null);
await db.exec(`set test.uid='${user}'`);
const ended=(await visit(uuid(3),'end',uuid(1))).rows[0].v;
assert.equal(ended.visit_kind,'end');assert.equal((await ws()).is_open,true);
assert.notEqual((await ws()).visits[0].ended_at,null);
await assert.rejects(visit(uuid(4),'end',uuid(1)),/selected open/);
await visit(uuid(5),'start',uuid(5),stop2);
await visit(uuid(6),'end',uuid(5),stop2);
const visits=(await ws()).visits;
assert.equal(visits.length,2);assert.equal(visits[1].route_stop_id,stop2);
assert.ok(visits.every(v=>v.work_date==='2026-09-30'));
// A legacy GPS capture is not guessed to be a visit start/end.
await save(capture);await assert.rejects(visit(capture),/legacy capture/);
await db.exec('reset role');await clockOut();
await db.exec(`update private.route_journey_rollouts set enabled=false`);await db.exec('set role authenticated');
assert.deepEqual((await visit(uuid(3),'end',uuid(1))).rows[0].v,ended);
assert.equal((await db.query(`select public.route_journey_visit_exact('${uuid(3)}') v`)).rows[0].v.visit_kind,'end');
await assert.rejects(visit(uuid(7)),/disabled|closed/);
await assert.rejects(db.query('select * from private.route_journey_visit_events'),/permission denied/);
await db.exec('begin isolation level repeatable read');await assert.rejects(visit(uuid(8)),/read committed/);await db.exec('rollback');
await db.exec('set role anon');await assert.rejects(db.query(`select public.route_journey_visit_workspace('${source}')`),/permission denied/);
await db.close();console.log('PASS visits: OFF, personal source, two visits, midnight source date, exact retries, atomic rejection, end != clock-out, unfinished clock-out rejection, legacy isolation');
