import fs from 'node:fs';
import assert from 'node:assert/strict';
const {PGlite}=await import(process.argv[2]);
const baseline=fs.readFileSync('tool/verify_expense_personal_submission.mjs','utf8');
const anchor=" console.log('PASS expense personal scope, immutable retry, actor isolation, amount/date validation, incurred month, rejected and retired history; no payroll writes');";
assert.ok(baseline.includes(anchor));
const extra=`
 await db.exec('reset role');
 await db.exec(\`create table company_approval_assignees(company_id uuid,user_id uuid);
 create table customers(id uuid primary key,company_id uuid,name text);
 create table partner_companies(id uuid primary key,company_id uuid,name text);
 insert into company_approval_assignees values('\${company}','\${other}');
 insert into customers values('\${id(30)}','\${company}','Customer'),('\${id(31)}','\${foreignCompany}','Foreign');
 insert into partner_companies values('\${id(32)}','\${company}','Subcontractor');\`);
 await db.exec(fs.readFileSync('supabase/migrations/20261010140111_expense_review_allocation.sql','utf8'));
 await db.exec(\`set role authenticated;set test.actor='\${actor}'\`);
 const workspace=()=>call(\`public.expense_review_workspace('\${company}','2026-09-01')\`);
 const command=(n,revision,action,category=null,party=null)=>call(\`public.expense_review_command('\${id(n)}','\${id(10)}',\${revision},'\${action}',\${category ? "'"+category+"'" : 'null'},\${party ? "'"+party+"'" : 'null'})\`);
 await assert.rejects(workspace(),/reviewer required/);
 await assert.rejects(command(40,1,'approve'),/selected expense approver required/);
 await db.exec(\`set test.actor='\${other}'\`);
 assert.equal((await workspace()).claims.length,1);
 await assert.rejects(command(40,1,'allocate','customer',id(30)),/approve before allocation/);
 const approved=await command(40,1,'approve');assert.equal(approved.allocation,'ownCompany');assert.equal(approved.approval,'approved');assert.equal(approved.revision,2);
 assert.deepEqual(await command(40,1,'approve'),approved);
 await assert.rejects(command(40,1,'reject'),/fixed expense command differs/);
 await assert.rejects(command(41,2,'allocate','customer',id(31)),/company customer required/);
 const allocated=await command(41,2,'allocate','customer',id(30));assert.equal(allocated.counterparty_id,id(30));
 assert.equal((await command(42,3,'approve')).counterparty_id,id(30));
 await assert.rejects(command(43,2,'allocate','ownCompany'),/changed; reload/);
 const rejected=await command(43,3,'reject');assert.equal(rejected.approval,'rejected');assert.equal(rejected.counterparty_id,id(30));
 const settings=await call(\`public.set_expense_approvers('\${company}',array['\${actor}']::uuid[],1)\`);assert.equal(settings.settings_revision,2);
 await assert.rejects(command(44,4,'approve'),/selected expense approver required/);
 await db.exec('reset role');assert.equal((await db.query('select user_id from company_approval_assignees')).rows[0].user_id,other);
 await db.exec(\`set role authenticated;set test.actor='\${actor}'\`);
 assert.equal((await workspace()).can_review,true);
 const reapproved=await command(44,4,'approve');assert.equal(reapproved.allocation,'ownCompany');
 const subcontracted=await command(45,5,'allocate','subcontractor',id(32));assert.equal(subcontracted.counterparty_id,id(32));
 const own=await command(46,6,'allocate','ownCompany');assert.equal(own.counterparty_id,null);
 await assert.rejects(call(\`public.set_expense_approvers('\${company}',array['\${other}']::uuid[],2)\`),/require administrator/);
 await db.exec(\`set test.blocked='true'\`);await assert.rejects(workspace(),/unavailable/);
 console.log('PASS expense-specific assignees, approve to own company, allocation, rejected details, fixed command retries, version conflicts and unchanged other-page assignees');
`;
const source=baseline.replace("import fs from 'node:fs';",'').replace("import assert from 'node:assert/strict';",'').replace('const {PGlite}=await import(process.argv[2]);','').replace(anchor,extra);
await new (Object.getPrototypeOf(async function(){}).constructor)('fs','assert','PGlite',source)(fs,assert,PGlite);
